README.md: Update installation instructions
This was failing as there are multiple binary packages available and `cargo` doesn't know which one to install

```
$ cargo install --git https://github.com/jfrimmel/cargo-valgrind
    Updating git repository `https://github.com/jfrimmel/cargo-valgrind`
error: multiple packages with binaries found: cargo-valgrind, corpus, ffi-bug, program-aborts. When installing a git repository, cargo will always search the entire repo for any Cargo.toml.
Please specify a package, e.g. `cargo install --git https://github.com/jfrimmel/cargo-valgrind cargo-valgrind`
```